name: Shell Commands

on:
  - push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          python -V
  run_another_shell_command:
    runs-on: ubuntu-22.04
    steps:
      - name: curl google.com
        run: curl https://google.com
      - name: python version
        run: python -V
      - name: python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-on-windows:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
